# Generated by Django 6.1.1 on 2026-09-19 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('specialty', models.CharField(max_length=150)),
                ('professional_data_link', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'mysite_doctor',
            },
        ),
        migrations.CreateModel(
            name='medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('dosage_standard', models.CharField(max_length=100)),
                ('target_disease', models.CharField(default='General', max_length=150)),
                ('description', models.TextField(blank=True)),
                ('alternatives', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'mysite_medication',
            },
        ),
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('dob', models.CharField(max_length=50)),
                ('passcode', models.CharField(default='patient123', max_length=255)),
                ('compliance_rate', models.IntegerField(default=95)),
            ],
            options={
                'db_table': 'mysite_patient',
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_issued', models.DateTimeField(auto_now_add=True)),
                ('pack_unique_id', models.CharField(max_length=100)),
                ('ai_approval_status', models.CharField(default='PENDING', max_length=50)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.doctor')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core_app.patient')),
                ('prescribed_meds', models.ManyToManyField(db_table='mysite_prescription_meds', to='core_app.medication')),
            ],
            options={
                'db_table': 'mysite_prescription',
            },
        ),
    ]
